### ISSUE TITLE
meteor files attempts to remove original version twice

### ISSUE THREAD

**Issue by s-ol** [VeliovGroup/Meteor-Files#127]
On creating our upload fileRefs, we add width and height to the `versions.original.meta` field, generate other versions and finally update the entry in the mongo collection.

when deleting the files via `FilesCollection.remove()` the original version get's deleted twice, causing this cryptic error in the server console:
```
I20160704-19:10:41.475(2)? Exception in callback of async function: TypeError: object is not a function
I20160704-19:10:41.626(2)?     at packages/mongo/collection.js:651:5
I20160704-19:10:41.626(2)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160704-19:10:41.627(2)?     at packages/meteor/dynamics_nodejs.js:123:1
I20160704-19:10:41.627(2)?     at packages/mongo/mongo_driver.js:322:7
I20160704-19:10:41.628(2)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160704-19:10:41.656(2)? Exception in callback of async function: TypeError: object is not a function
I20160704-19:10:41.657(2)?     at packages/mongo/collection.js:651:5
I20160704-19:10:41.657(2)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160704-19:10:41.658(2)?     at packages/meteor/dynamics_nodejs.js:123:1
I20160704-19:10:41.658(2)?     at packages/mongo/mongo_driver.js:322:7
I20160704-19:10:41.658(2)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

after looking at the code it seemed like the double-unlink was what's going on, and I could confirm it with an `strace`:
```
pid  2292] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=2584, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
[pid  2317] unlink("../../../../../../data/serviceFiles/qcsvuRFCAwTmmXw2T.png_64.png" <unfinished ...>
[pid  2316] unlink("../../../../../../data/serviceFiles/qcsvuRFCAwTmmXw2T.png_128.png" <unfinished ...>
[pid  2317] <... unlink resumed> )      = 0
[pid  2316] <... unlink resumed> )      = 0
[pid  2317] unlink("../../../../../../data/serviceFiles/qcsvuRFCAwTmmXw2T.png_256.png") = 0
[pid  2315] unlink("../../../../../../data/serviceFiles/qcsvuRFCAwTmmXw2T.png_512.png") = 0
[pid  2317] unlink("../../../../../../data/serviceFiles/qcsvuRFCAwTmmXw2T.png" <unfinished ...>
[pid  2316] unlink("../../../../../../data/serviceFiles/qcsvuRFCAwTmmXw2T.png") = 0
[pid  2317] <... unlink resumed> )      = -1 ENOENT (No such file or directory)
```
as you can see the main file is attempted to be removed twice.

I don't think we changed anything relevant and afaik the `"original"` version key is in the collection per default, so I suppose this is a new bug as of 1.6(.1)?

**Comment by dr-dimitru** [comment]
I can't reproduce it on my end, please test version `1.6.2`  from `dev` branch on your end. This issue should be fixed.

**Comment by dr-dimitru** [comment]
Whoops, accidentally closed this issue

**Comment by s-ol** [comment]
hm, weird. I would have expected dd3cd93d8d7f62bdf8f24a83fc6e775bb8d34d60 to fix this, but I cloned Meteor-Files in the packages directory and the error persists. The package must've been loaded though because initial startup upgrade the package version to `ostrio:files@1.6.2`.

**Comment by dr-dimitru** [comment]
@s-ol `packages/mongo/collection.js:651:5` is out of my control.
Have you specified callback? In `remove()` method?

**Comment by s-ol** [comment]
@dr-dimitru not with 1.6.2, but with the last version it didn't help.

**Comment by dr-dimitru** [comment]
@s-ol could you please post the code used to remove files? And callback if you have it

**Comment by s-ol** [comment]
It is very simple:

`SketchFiles.remove({ 'meta.serviceCaseId': serviceCaseId });`

SketchFiles is the `FilesCollection` instance.

**Comment by dr-dimitru** [comment]
try to `SketchFiles.find({ 'meta.serviceCaseId': serviceCaseId }).remove()`

**Comment by dr-dimitru** [comment]
@s-ol any news?

**Comment by s-ol** [comment]
Sorry for my long feedback times, I don't work on the project daily and sometimes other things have a higher priority to me. I tried the latest meteor-files with the commit linked above, but the error persists both with `Collection.remove(mongoSelector)` and `Collection.find(mongoSelector).remove()`.

**Comment by dr-dimitru** [comment]
@s-ol Could you post all code related to MF package? Can't reproduce it, neither find a place it's coming from

**Comment by dr-dimitru** [comment]
@s-ol is this fixed? Or you're still having this issue?

**Comment by dr-dimitru** [comment]
@s-ol any news in your end?

**Comment by dr-dimitru** [comment]
Please reopen if you still having this issue
