### ISSUE TITLE
Unknown key in field isBase64

### ISSUE THREAD

**Issue by FinnFrotscher** [VeliovGroup/Meteor-Files#205]
I get a weird error when trying to upload `base64` data.

This is the code:

```
        const data = {}
        data.file = base64
        data.streams = 'dynamic'
        data.chunkSize = 'dynamic'
        data.isBase64 = true
        console.log(data);

        Videos.insert(data, true);
```

This is the output:
```
Object {file: "data:video/webm;base64,GkXfo59ChoEBQveBAULygQRC84E…1ArB9TK4U3ilQ+glf94BFJanLBOLZ5xrw7kv1siIIdxSTpQAA", streams: "dynamic", chunkSize: "dynamic", isBase64: true}

match.js:39 Uncaught Error: Match error: Unknown key in field isBase64
```

**Comment by dr-dimitru** [comment]
Hi @FinnFrotscher ,

 1. Could you post full error stack?
 2. Debug logs?
 3. How are you getting base64 string? Where it comes from?

Quick guess:
You need to remove `;base64` from Base64 string:
```js
data.file = base64.replace(';base64', '');
```

If this will solve your issue, I'll confirm it as bug.

**Comment by dr-dimitru** [comment]
Okay, 
I can not reproduce this error, but I got similar one, which is solved when you add `fileName` property. __`fileName` is required to set a name of the file__, and your code is missing it.

**Comment by dr-dimitru** [comment]
Please update to v1.7.2, there was various fixes

**Comment by FinnFrotscher** [comment]
Hi
I added `base64.replace(';base64', '')` and now the `file field` starts with `data:video/webm,GkXfo59ChoEBQveB……`. 
But i still get the error `match.js:39 Uncaught Error: Match error: Unknown key in field isBase64` 

Meteor is still at `1.3.5` because I have issues with `mupx` when i upgrade to `1.4.1`.  
Thus, when I update `ostrio:files` I get: `ostrio:files  downgraded from 1.7.2 to 1.6.6` once i run meteor.


The `base64` is returned by `RecordRTC`, which in turn gets its `mediaStream` from `navigator.mediaDevices.getUserMedia`.

```
const videoRecorder = RecordRTC(this.state.mediaStream, { type: 'video' })

////

videoRecorder.getDataURL((base64) => {
        const uploadData = {}
        uploadData.file = base64.replace(';base64', '');
        uploadData.fileName = 'random'
        uploadData.streams = 'dynamic'
        uploadData.chunkSize = 'dynamic'
        uploadData.isBase64 = true
        console.log(uploadData);


        Videos.insert(uploadData, true);
}
```

**Comment by FinnFrotscher** [comment]
My Collection.js:
```
import { FilesCollection } from 'meteor/ostrio:files';

export const Videos = new FilesCollection({
  collectionName: 'Videos',
  allowClientCode: false, // Disallow remove files from Client
  onBeforeUpload: function (file) {
    console.log('called');
  }
});
```

which gets imported: `import {Videos} from '../../lib/Collection.js'`

**Comment by dr-dimitru** [comment]
Okay, I need full log in debug mode and full error stack.
I've tried your base64 encoded string before releasing 1.7.2 works fine for me.

Also, we have seen weird issues which appears in ES6 but not on regular JS (ES5). Could you do quick test on JS? There is no need to import `FilesCollection` as it in global scope, and just bind `Videos` to global scope via: `this.Videos = new FilesCollection({...});`

After you bind `Videos` to global scope you can try to upload base64 string right from browser's console.

**Comment by FinnFrotscher** [comment]
When `FilesCollection({debug:true})` I get `[FilesCollection] [insert()]` logged from the `ostrio_files` package.

How do i get the full error stack?

Videos is now is now in global scope, but still the same error.

I tested with ES5 and still same error.

**Comment by FinnFrotscher** [comment]
`ostrio:files  downgraded from 1.7.2 to 1.6.6`
my `ostrio:files` ist at 1.6.6. I cant update to a higher version.

**Comment by dr-dimitru** [comment]
> my ostrio:files ist at 1.6.6. I cant update to a higher version.

Why? What Meteor version?

**Comment by FinnFrotscher** [comment]
METEOR@1.3.5.1
Cant update to Meteor 1.4 because there is an issue with `mup deploy`, `ssl certification`, and `meteor 1.4`

**Comment by FinnFrotscher** [comment]
#https://github.com/kadirahq/meteor-up/issues/257

**Comment by FinnFrotscher** [comment]
That would be amazing 💃

**Comment by dr-dimitru** [comment]
@FinnFrotscher answered to kadirahq/meteor-up#257 thread

**Comment by dr-dimitru** [comment]
And remove `force-ssl` package
```shell
meteor remove force-ssl
```

**Comment by dr-dimitru** [comment]
So you issue caused bu older version as base64 support appeared only at 1.7.1

**Comment by FinnFrotscher** [comment]
With the newest version of meteor this works just fine :)

**Comment by dr-dimitru** [comment]
You got it updated?

**Comment by FinnFrotscher** [comment]
yes, Once i updated meteor to 1.4 i could update `files` to 1.7. now everything works fine.

**Comment by dr-dimitru** [comment]
So assume this one as fixed
