### ISSUE TITLE
Meteor 1.6.1-beta.18 crashes on file download - Error: Can't wait without a fiber

### ISSUE THREAD

**Issue by menelike** [VeliovGroup/Meteor-Files#538]
*extracted from https://github.com/meteor/meteor/pull/9274#issuecomment-351754992*

Not sure if this is a task for this project or Meteor, but might be worth to be mentioned:

> When I upgraded to meteor 1.6.1-beta.18, the ostrio:files package showed an error as below, something releated to FilesCollection.WebApp.connectHandlers.use, and I could not load any images from the meteor server.

**Comment by dr-dimitru** [comment]
Thank you @menelike , update is coming

**Comment by dr-dimitru** [comment]
Hello @menelike ,

Thank you for submitting this one.
Unfortunately I can not reproduce it.

I need more info on that one.
 1. Platform (OS: Win/Mac/Linux)
 2. File type and size
 3. All used env.vars, like `ROOT_URL` and etc.
 4. Browser name and its version
 5. Full server/client logs and error with enabled "`debug` mode"

I've updated our [Meteor-Files demo app, now it's in separate branch](https://github.com/VeliovGroup/Meteor-Files-Demos/tree/1.6.1-beta.18/demo).

/cc @alexgzhou

**Comment by alexgzhou** [comment]
Hi @dr-dimitru, thank your for /cc me!
I have made a small project to reproduce the issue, below is the github address, again, thank your for your great job~
[https://github.com/alexgzhou/meteorFilesDemo](url)

**Comment by dr-dimitru** [comment]
@alexgzhou can not reproduce, everything works well.

![screen shot 2017-12-18 at 5 08 44 pm](https://user-images.githubusercontent.com/1686778/34109956-4461cfa6-e416-11e7-8a27-9e5c329ac751.png)
![screen shot 2017-12-18 at 5 08 39 pm](https://user-images.githubusercontent.com/1686778/34109959-44abc444-e416-11e7-9934-434478ec7782.png)

**Comment by alexgzhou** [comment]
so odd!!! @dr-dimitru, just a monent, I will upload my error page

**Comment by dr-dimitru** [comment]
@alexgzhou please update this thread with next info:

 1. Platform (OS: Win/Mac/Linux), version/release number
 2. File type and size
 3. All used env.vars, like `ROOT_URL` and etc.
 4. Browser name and its version
 5. Full server/client logs and error with enabled "`debug` mode"

On my setup - MacOS 10.13.2 (17C88), Safari v11.0.2 and Chrome v62.0.3202.94 - everything is fine.

Could someone else confirm issue persistence on Ubuntu?

**Comment by alexgzhou** [comment]
1. Ubuntu 16.04 and 17.10 64 bit
2. PNG type and 1.2MB
3. no env.vars and barely start with `meteor`
4. Chrome 63.0.3239.108
5. As below:
```
just a monent...
```

**Comment by menelike** [comment]
@dr-dimitru tried to make some tests on https://github.com/VeliovGroup/Meteor-Files-Demos/commit/83e93cbea5aec8f686d1f9eba9081331bac18998 but I can't start the project, `fourseven:scss@3.13.0` throws errors. Need some time to dig into this.

**Comment by dr-dimitru** [comment]
@menelike do not update it, use constraint version `fourseven:scss@3.3.3`, older releases never worked for me

**Comment by menelike** [comment]
@dr-dimitru 

I did not change the version of `fourseven` (https://github.com/VeliovGroup/Meteor-Files-Demos/blob/83e93cbea5aec8f686d1f9eba9081331bac18998/demo/.meteor/versions#L38)

Also if I set `fourseven` to `3.3.3` I get
`Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.3/darwin-x64-57_binding.node": HTTP error 404 Not Found`

I'm afraid that I need another demo project to reproduce this error :(

**Comment by alexgzhou** [comment]
@menelike 
Could you reproduce the error using my [project](https://github.com/alexgzhou/meteorFilesDemo)?

**Comment by menelike** [comment]
@alexgzhou Thank you very much, yes I can reproduce this problem with your project.

```
[[[[[ ~/WebstormProjects/meteorFilesDemo ]]]]]

=> Started proxy.
=> Started your app.

=> App running at: http://localhost:3000/
I20171219-11:00:37.029(1)? resize arg
I20171219-11:00:37.071(1)? arg 500
I20171219-11:00:37.216(1)? resize arg
I20171219-11:00:37.217(1)? arg 200
W20171219-11:00:37.378(1)? (STDERR) Error: Can't wait without a fiber
```

*osX/10.12.6 (16G1036)/Darwin Kernel Version 16.7.0*

**Comment by dr-dimitru** [comment]
@menelike I've double-checked [meteor-files `1.6.1-beta.18` branch](https://github.com/VeliovGroup/Meteor-Files-Demos/tree/1.6.1-beta.18/demo), all works fine. Try to set your DNS to Google public DNS.

See full log below:
![screen shot 2017-12-19 at 1 16 34 pm](https://user-images.githubusercontent.com/1686778/34152270-1035a80c-e4bf-11e7-9b19-b20201d48d63.png)


Where this logs coming from, can not find those lines in a [`meteorFilesDemo` rep](https://github.com/alexgzhou/meteorFilesDemo)?:
```
I20171219-11:00:37.029(1)? resize arg
I20171219-11:00:37.071(1)? arg 500
I20171219-11:00:37.216(1)? resize arg
I20171219-11:00:37.217(1)? arg 200
```

**Comment by alexgzhou** [comment]
@dr-dimitru These logs are from a node package `quickthumb` which I used to generate image thumbs.
```
I20171219-11:00:37.029(1)? resize arg
I20171219-11:00:37.071(1)? arg 500
I20171219-11:00:37.216(1)? resize arg
I20171219-11:00:37.217(1)? arg 200
```

**Comment by alexgzhou** [comment]
@dr-dimitru 
I have fixed a minor bug in the demo project, would you update your local git repository and try to click the `UPLOAD ALL` button, see if an error would show up~

**Comment by menelike** [comment]
@alexgzhou I just updated your project to 1.6.1-beta.21 and could not see any error anymore. It seems that is was a Meteor issue and is fixed by now. Can you confirm this?

**Comment by alexgzhou** [comment]
@menelike I still have the issue. I will try to uninstall and reinstall the entire meteor env, and try it again.

**Comment by dr-dimitru** [comment]
@menelike @alexgzhou please close this issue if it's solved in `1.6.1-rc.1`.

**Comment by alexgzhou** [comment]
@dr-dimitru I still have the issus upgraded to `1.6.1-rc.1`.

**Comment by dr-dimitru** [comment]
Hello @alexgzhou ,

Any progress on this one?
I sill can not reproduce the issue.

**Comment by alexgzhou** [comment]
@dr-dimitru I have meteor updated to 1.6.1-rc.2, and tried in Ubuntu 16.04, 17.10 and Mac OS 11, still have the issue, upload is fine, collection records fetch is fine, I could use Collection.link(file, 'original') to get a resource url, but when I copy the url and open it in a new tab or with postman, I got the error.

**Comment by menelike** [comment]
I just tested https://github.com/alexgzhou/meteorFilesDemo against `1.6.1-beta.18` and `1.6.1-rc.6` and both start fine, but fail after I load the page with `Error: Can't wait without a fiber`.

It seems that https://github.com/VeliovGroup/Meteor-Files/blob/master/server.js#L419 is causing the trouble but I don't know why.

**Comment by dr-dimitru** [comment]
@menelike thank you for update, I'm going to tun more tests and try to find out why this is happening.
I'll be glad if @mitar could take a look at this thread and give us a clue.

**Comment by mitar** [comment]
Why you think I could help here?

**Comment by menelike** [comment]
@dr-dimitru 

I ran a couple of test for some hours and I can reproduce this problem with the following steps:

1. clone https://github.com/alexgzhou/meteorFilesDemo
2. meteor update --release 1.6.1-beta.17
3. meteor run
=> works, then
4. meteor update --release 1.6.1-beta.18
5. meteor run
=> crashes with `Error: Can't wait without a fiber`
6. FYI: If you then downgrade again per meteor update --release 1.6.1-beta.17
make sure that you remove the package version 
7. rm -rf .meteor/version
as they are still referring to beta.18 which will result in beta.17 crashing with `Error: Can't wait without a fiber` as well.

I think that https://github.com/meteor/meteor/commit/9a391d9b04dac40758c6f791db2b622505235aa8#diff-79c5e18978e1bfa64cbb9edb380f2920 might cause this. As soon as this is reproducible for other we should make an issue in the Meteor project.

**Comment by dr-dimitru** [comment]
@mitar I was only hoping :) could you //cc someone from MDG?
Mb @benjamn could help to find out why behavior of  `WebApp.connectHandlers.use` is changed?

To me, it seems like a breaking change.

**Comment by dr-dimitru** [comment]
@menelike thank you for reproduction steps. Going to try it tonight.

**Comment by mitar** [comment]
Sorry, no capacity for this right now. I also have not been following changes to this part of Meteor.

**Comment by benjamn** [comment]
I think I can fix this!

**Comment by dr-dimitru** [comment]
Looks like fix is arrived - https://github.com/meteor/meteor/commit/3b18863
Thank you @benjamn 👏 🎉

**Comment by menelike** [comment]
Happy to confirm that [1.6.1-rc.7](https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.6.1-rc.7) fixed this issue!

Great work everybody!
