### ISSUE TITLE
downloadCallback doesn't receive userId

### ISSUE THREAD

**Issue by s-ol** [VeliovGroup/Meteor-Files#97]
In `downloadCallback` `this.userId` and `this.user()` always are/return `null`. If they do not work why are they in the Context?

Also, the same works in `protected`. What's the difference between `protected` and `downloadCallback` other than that? If it works in `protected` why is there `downloadCallback` and are there any side effects of using `protected` for download permissions?

**Comment by dr-dimitru** [comment]
- `downloadCallback` - Is mainly created to do something when user already received the file, like increment download count
 - `protected` - Was created to protect files from unauthorised download

**Comment by dr-dimitru** [comment]
@s-ol show me some of your code and tell more about current issue, than I'll help you

**Comment by s-ol** [comment]
Current issue is mostly confusion. Apparently I am using protected like it's supposed to be used now:

```
  protected: function prot(fileObject) {
    if (Meteor.isServer && fileObject) {
      const { meta: { asdId } } = fileObject;

      const asd = ASD.findOne(asdId);
      if (!asd) return false;
      if (!asd.editableBy(this.userId)) return 403;
    }

    return true;
  },
```

Still, I think `this.userId` and `this.user()` should either be made to work in `downloadCallback` or removed from the context. And maybe the wiki should be edited to include what you just said:

> * `downloadCallback` - Is mainly created to do something when user already received the file, like increment download count
* `protected` - Was created to protect files from unauthorised download

**Comment by dr-dimitru** [comment]
Hi @s-ol ,

Sorry, for silence on my end. I want to give you an update: *I'm still working on this. I'll come back with solution later.*

Let me know if you have any updates on your end.

**Comment by s-ol** [comment]
Actually I think it might've been an issue more or less on our side - we had upgraded to the meteor beta and iirc a cookie-related package (might have) had a regression. I think we had the issue with "protected" too at a later stage and resolved it with another upgrade somehow but maybe @menelike can remember and shed some light on that.

**Comment by dr-dimitru** [comment]
Try just to move `ostrio:files` higher on `.meteor/packages` file, so it will bind cookie middleware before any other package

**Comment by s-ol** [comment]
I'll try to confirm this isn't an issue with meteor-files one way or another and get back at you tomorrow; if I don't just remind me again.

**Comment by hamzapurra** [comment]
I am facing the same issue; this.userId is null in the protected and downloadCallback callbacks

**Comment by dr-dimitru** [comment]
Hi @s-ol and @hamzapurra ,
This issue is fixed in `dev` branch, see [10aa57505fe92dd532e0b9b0adf5d118bc22945f](https://github.com/VeliovGroup/Meteor-Files/commit/10aa57505fe92dd532e0b9b0adf5d118bc22945f).
Please test it on your end. Waiting for your response.

**Comment by s-ol** [comment]
Unfortunately the error persists using ostrio:files dev branch / version 1.6.0; userId is missing in `protected` also.

**Comment by dr-dimitru** [comment]
@s-ol
1. What account packages is installed in your project?
2. Could you post some of your relate code?

**Comment by s-ol** [comment]
we are using `accounts-password` (1.1.11) and `ostrio:cookies` (2.0.3) under meteor `1.3.4`. The only code I can think of as related is the above snippet of `protected`, nothing else touches on this directly. File uploads work "normally" and we are not touching the routes to the images/files in any way.

**Comment by dr-dimitru** [comment]
Weird, I'm testing it right now and it works
1. Could you add `accounts-base` package to `.meteor/packages`
2. Check existence of `meteor_login_token` cookie

**Comment by dr-dimitru** [comment]
@s-ol any news?

**Comment by s-ol** [comment]
@dr-dimitru sorry for not replying earlier, but there wasn't anything new we found out to give info until today, when we realised the problem was simply caused by the cookies not being available between 127.0.0.1 and localhost and a mismatch of the request domain/url and the ROOT_URL environment variable default in some of our development environments.

**Comment by dr-dimitru** [comment]
@s-ol thank you for update on it. Glad you solved it

**Comment by perusopersonale** [comment]
I'm facing this issue too. I'm not using ostrio:cookies, I'm using account-package, meteor_login_token is present in cookie and in request header.
I've already try to move package on top of packages list without any result.
The strange fact is that sometimes it works sometimes not, it was working fine but when I show progress to my boss it fail..it's always like that.
Anyway nice package.

**Comment by s-ol** [comment]
@perusopersonale what ROOT_URL are you setting and which URLs do you visit to show your app?

**Comment by perusopersonale** [comment]
I'm making some test in LAN, the app is not yet in production.
I'm running meteor on a linux machine with ROOT_URL its ip,
so I run meteor with: ROOT_URL=xxx.xxx.xxx.xxx:3000 meteor, and for connect I use that url.
